GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIiwiaWF0IjoxNTgzNzQ0OTM1fQ.4HZMdg-QjTz8DLZDK2IIwE2vxpGnId_UKEsbYeXp6M4

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Joe"
}