GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIiwiaWF0IjoxNTgzNzQ1MTk4fQ.K1zHucU-sk5GrNIOf3dqrwx6ElMuzAyBTTNS0xpFJjs

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Joe"
}